name: a2f_sdk
description: App Anvil Flutter SDK
version: 7.1.0
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  equatable: ^2.0.5
  flext: ^1.2.0
  flutter: { sdk: flutter }
  formz: ^0.7.0
  intl: ^0.19.0
  meta: ^1.10.0
  rxdart: ^0.27.5
  the_umpteenth_logger:
    git:
      url: git@github.com:gianmarcocalbi/the_umpteenth_logger.git
      path: packages/the_umpteenth_logger
      ref: 1.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^6.0.0
