name: a2f_sdk
description: App Anvil Flutter SDK
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  equatable: ^2.0.5
  flext: ^1.0.0
  flutter: { sdk: flutter }
  flutter_bloc: ^8.1.3
  formz: ^0.6.1
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path: ^1.8.3
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  the_umpteenth_logger: 
    git: 
      url: git@github.com:gianmarcocalbi/the_umpteenth_logger.git
      path: packages/the_umpteenth_logger
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
